services:
    ganstaz.legend.collection:
        class: phpbb\di\service_collection
        arguments:
            - '@service_container'
        tags:
            - { name: service_collection, tag: gzo.web.legend }

    ganstaz.legend.manager:
        class: ganstaz\legend\core\manager
        arguments:
            - '@ganstaz.legend.collection'

    ganstaz.legend.achievements.base:
        abstract: true
        arguments:
            - '@cache'
            - '@dbal.conn'
            - '%ganstaz.web.tables.legend%'
            - '%ganstaz.web.tables.achievements%'
            - '%ganstaz.web.tables.achievements_user%'

# Achievement types
    ganstaz.legend.posts:
        class: ganstaz\legend\core\type\posts
        shared: false
        parent: ganstaz.legend.achievements.base
        calls:
            - [set_name, ['posts']]
        tags:
            - { name: gzo.web.legend }

    ganstaz.legend.topics:
        class: ganstaz\legend\core\type\topics
        shared: false
        parent: ganstaz.legend.achievements.base
        calls:
            - [set_name, ['topics']]
        tags:
            - { name: gzo.web.legend }

    ganstaz.legend.anniversary:
        class: ganstaz\legend\core\type\anniversary
        shared: false
        parent: ganstaz.legend.achievements.base
        calls:
            - [set_name, ['anniversary']]
        tags:
            - { name: gzo.web.legend }

    ganstaz.legend.special:
        class: ganstaz\legend\core\type\special
        shared: false
        parent: ganstaz.legend.achievements.base
        calls:
            - [set_name, ['special']]
        tags:
            - { name: gzo.web.legend }
