parameters:
    ganstaz.gzo.tables.legend: '%core.table_prefix%gzo_achievements'
    ganstaz.gzo.tables.achievements: '%core.table_prefix%gzo_achievement_types'
    ganstaz.gzo.tables.achievements_user: '%core.table_prefix%gzo_achievements_user'
